version: "3.9"

services:
  db:
    container_name: django-template-database
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=192.168.0.2
      - POSTGRES_PORT=5432
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  redis:
    container_name: django-template-redis
    image: redis:7
    networks:
      app_net:
        ipv4_address: 192.168.0.5

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: django-template-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      app_net:
        ipv4_address: 192.168.0.4

  flower:
    container_name: django-template-flowerui
    image: mher/flower
    restart: always
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - redis
      - celery
      - rabbitmq
    links:
      - redis
      - celery
      - rabbitmq
    networks:
      app_net:
        ipv4_address: 192.168.0.6

  pgadmin:
    container_name: django-template-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      # PGADMIN_LISTEN_PORT = 80
    ports:
      - "5050:80"
    volumes:
      - django-template-pgadmin-data:/var/lib/pgadmin
    networks:
      app_net:
        ipv4_address: 192.168.0.3

volumes:
  postgres_data:
  django-template-pgadmin-data:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1
