version: "3.9"

services:
  db:
    image: postgres:latest
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db

  redis:
    image: redis:7

  celery:
    build:
      context: ../
    restart: always
    command: celery -A core worker -l info
    env_file:
      - ../.env
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_SECRET_KEY=dj4ng0_sup3r_s3cr3t_k3y
      - DJANGO_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_BACKEND=redis://redis:6379/0
    volumes:
      - ../:/usr/src/app/
    depends_on:
      - db
      - redis
      - web

  web:
    container_name: CONTAINERNAME
    build:
      context: ../
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ../.env
    volumes:
      - ../:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DJANGO_SECRET_KEY=dj4ng0_sup3r_s3cr3t_k3y
      - DJANGO_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db

networks:
  django-template:
