version: "3.9"

services:
  celery:
    container_name: django-template-celery
    build:
      context: ../
      target: production
      dockerfile: ./django/Dockerfile
    restart: always
    command: celery -A core worker -l info
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY=dj4ng0_sup3r_s3cr3t_k3y
      - DJANGO_DEBUG=1
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_BACKEND=redis://redis:6379/0
    volumes:
      - ../django/:/usr/src/app/
    depends_on:
      - db
      - redis
      - backend
      - rabbitmq
    links:
      - redis
      - db
      - rabbitmq

  backend:
    container_name: django-template-backend
    build:
      context: ../
      target: production
      dockerfile: ./django/Dockerfile
    restart: always
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8080 --workers 4 --log-level debug --reload
    expose:
      - 8080
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY=dj4ng0_sup3r_s3cr3t_k3y
      - DJANGO_DEBUG=1
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_BACKEND=redis://redis:6379/0
    volumes:
      - ../django/:/usr/src/app/
    depends_on:
      - redis
      - db
      - rabbitmq
    links:
      - redis
      - db
      - rabbitmq

  nginx:
    container_name: django-template-nginx
    build:
      context: ../
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    links:
      - backend

volumes:
  postgres_data:

