version: "3.9"

services:
  db:
    container_name: django-template-database
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_HOST=5432

  redis:
    container_name: django-template-redis
    image: redis:7

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name: django-template-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  flower:
    container_name: django-template-flowerui
    image: mher/flower
    restart: always
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - redis
      - celery
      - rabbitmq

volumes:
  postgres_data:
