version: "3.9"

services:
  celery:
    container_name: django-template-celery
    build:
      context: ./..
      target: development
      dockerfile: ./django/Dockerfile
    restart: always
    command: celery -A core worker -l info
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY=dj4ng0_sup3r_s3cr3t_k3y
      - DJANGO_DEBUG=1
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_BACKEND=redis://redis:6379/0
    volumes:
      - ../django/:/usr/src/app/
    depends_on:
      - db
      - redis
      - backend
      - rabbitmq

  backend:
    container_name: django-template-backend
    build:
      context: ./..
      target: development
      dockerfile: ./django/Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ../.env
    volumes:
      - ../django:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY=dj4ng0_sup3r_s3cr3t_k3y
      - DJANGO_DEBUG=1
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
      - rabbitmq

volumes:
  postgres_data:
